name: Build and Deploy to Kubernets

on:
  push:
    branches:
      - dev
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  #IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  #IBM_CLOUD_REGION: us-south
  DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #ICR_NAMESPACE: ${{ secrets.ICR_NAMESPACE }}
  REGISTRY_HOSTNAME: slackbr
  IMAGE_NAME: action-demo
  #IKS_CLUSTER: bq1sm2gd0sjtps7ajoa0 # name or id of cluster
  #DEPLOYMENT_NAME: hello-python
  #PORT: 5001

jobs:

  setup-build-publish-deploy:
      name: Setup, Build, Publish, and Deploy
      runs-on: ubuntu-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Download and Install IBM Cloud CLI
      # - name: Install IBM Cloud CLI
      #   run: |
      #     curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
      #     ibmcloud --version
      #     ibmcloud config --check-version=false
      #     ibmcloud plugin install -f kubernetes-service
      #     ibmcloud plugin install -f container-registry

      # Authenticate with IBM Cloud CLI
      # - name: Authenticate with IBM Cloud CLI
      #   run: |
      #     ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g default
      #     ibmcloud cr region-set "${IBM_CLOUD_REGION}"
      #     ibmcloud cr login
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
      # Build the Docker image
      - name: Build with Docker
        run: |
          #docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          docker build -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .

      # Push the image to Container Registry
      - name: Push the image to ICR
        run: |
          docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$GITHUB_SHA
    
  # Deploy the Docker image to the IKS cluster
      # - name: Deploy to IKS
      #   run: |
      #     ibmcloud ks cluster config --cluster $IKS_CLUSTER
      #     kubectl config current-context
      #     kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
      #     kubectl apply -f deployment.yaml
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
      #     kubectl apply -f service.yaml
      #     kubectl get services -o wide