name: Build and Deploy to Kubernets

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:

    CI:
      name: Build container
      #runs-on: ubuntu-latest
      runs-on: self-hosted 
      environment:
        name: ci
      env:
        GITHUB_SHA: ${{ github.sha }}
        REGISTRY_HOSTNAME: slackbr
        IMAGE_NAME: action-demo
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker hub login
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Github Short SHA
        run: |
          GITHUB_SHORT_SHA=$(echo "$GITHUB_SHA"|cut -c-5)
          export GITHUB_SHORT_SHA
          echo $GITHUB_SHORT_SHA
      
      - name: Build Docker image
        run: |
          #echo $GITHUB_SHORT_SHA
          docker build --file Dockerfile -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest
          
      - name: Push the image to Docker container registry
        run: |
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA"
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest        

    CDDEV:
        name: Dev Deployment
        #runs-on: ubuntu-latest
        runs-on: self-hosted
        environment:
          name: dev
        needs: CI
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        
        steps:
          - name: Configure kubeconfig
            uses: azure/k8s-set-context@v1
            with:
              method: kubeconfig
              kubeconfig: ${{ env.K8S_KUBECONFIG }}
              #cluster-type: generic
            env:
              K8S_KUBECONFIG: ${{secrets.K8S_KUBECONFIG}}
              
          - name: Checkout Ansible Repo
            uses: actions/checkout@v2
            with:
              repository: 'julianoslackbr/ansible-kubernetes'

          - name: Install Ansible
            run: |
              pip3 install pip --upgrade
              pip3 install kubernetes==11.0.0 openshift==0.11.0
              pip3 install ansible==2.9

          - name: Create kubernets vars
            run:  ansible-playbook sample-playbook-createvars.yml -v
            env:
              TAG: ${{ github.sha }}

          - name: Create kubernets manifests and deploy
            run: ansible-playbook sample-playbook-k8s.yml -v --skip-tags=apply

          - name: Install kubeval test tool
            run: |
              curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
              tar xf kubeval-linux-amd64.tar.gz -C /usr/local/bin/
              ln -s /usr/local/bin/kubeval /usr/bin/kubeval
              chmod +x /usr/local/bin/kubeval

          - name: Running kubeval test tool
            run: |
              for files in $(find ./k8s -type f); do
                kubeval $files
                test $? -ne 0 && exit 1
              end

          - name: Create kubernets manifests and deploy
            run: ansible-playbook sample-playbook-k8s.yml -v --tags=apply
