name: Build and Deploy to Kubernets

on:
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:

    CI:
      name: Build container
      runs-on: ubuntu-latest
      environment:
        name: ci
      env:
        GITHUB_SHA: ${{ github.sha }}
        REGISTRY_HOSTNAME: slackbr
        IMAGE_NAME: action-demo
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker hub login
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

      - name: Set Github Short SHA
        run: |
          GITHUB_SHORT_SHA=$(echo "$GITHUB_SHA"|cut -c-5)
          export GITHUB_SHORT_SHA
          echo $GITHUB_SHORT_SHA
      
      - name: Build Docker image
        run: |
          #echo $GITHUB_SHORT_SHA
          docker build --file Dockerfile -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest
          
      - name: Push the image to Docker container registry
        run: |
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA"
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest        

    CDDEV:
        name: Dev Deployment
        runs-on: ubuntu-latest
        environment:
          name: dev
        needs: CI
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          GITHUB_SHA: ${{ github.sha }}
        steps:
          - name: Checkout Ansible Repo
            uses: actions/checkout@v2
            with:
              repository: 'julianoslackbr/ansible-kubernetes'

          - name: Install Ansible
            run: |
              pip3 install pip --upgrade
              pip3 install kubernetes==11.0.0 openshift==0.11.0
              pip3 install ansible==2.9

          - name: Create kubernets vars
            run:  ansible-playbook sample-playbook-createvars.yml -v
            env:
              TAG: ${{ github.sha }}

          - name: List files
            run: |
              ls -alt
              cat secrets-vars-file.yaml kubernetes-vars-file.yaml
              
          - name: Create kubernets manifests and deploy
            run: |
              ansible-playbook sample-playbook-k8s.yml -vvvv
              ls -al ./k8s
              


    # # deploy hml
    # hml:
    #   name: Hml Variables
    #   runs-on: ubuntu-latest
    #   environment:
    #     name: hml
    #     url: "http://hml.teste.teste"
    #   needs: deploy-dev

    #   steps:
    #     - name: Run hml deployment 
    #       run: |
    #         echo "Deploy HML"
    #         echo ${{ secrets.DB_HOST }} > file.txt
    #         cat file.txt
    #         printenv
    #         echo "-------"
    #         ls -al
            
  # Deploy the Docker image to the IKS cluster
      # - name: Deploy to IKS
      #   run: |
      #     ibmcloud ks cluster config --cluster $IKS_CLUSTER
      #     kubectl config current-context
      #     kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
      #     kubectl apply -f deployment.yaml
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
      #     kubectl apply -f service.yaml
      #     kubectl get services -o wide