name: Build and Deploy to Kubernets

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:

    CI:
      name: Build container
      #runs-on: ubuntu-latest
      runs-on: self-hosted 
      environment:
        name: ci
      env:
        GITHUB_SHA: ${{ github.sha }}
        REGISTRY_HOSTNAME: slackbr
        IMAGE_NAME: action-demo
      
      outputs:
        SHORT_SHA: ${{ steps.shortSha.outputs.SHORT_SHA }}

      steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.test.outputs.exit_code == 0

      - name: Set Github Short SHA
        id: shortSha
        run: |
          GITHUB_SHORT_SHA=$(echo "$GITHUB_SHA"|cut -c-7)
          echo "::set-output name=SHORT_SHA::${GITHUB_SHORT_SHA}"
        if: steps.test.outputs.exit_code == 0
      
      - name: Build Docker image
        run: |
          docker build --file Dockerfile -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":${{ env.TAG }} .
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":${{ env.TAG }} "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest
        env:
          TAG: ${{ steps.shortSha.outputs.SHORT_SHA }}
        if: steps.test.outputs.exit_code == 0
          
      - name: Push the image to docker container registry
        run: |
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":${{ env.TAG }}
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest
        env:
          TAG: ${{ steps.shortSha.outputs.SHORT_SHA }}
        if: steps.test.outputs.exit_code == 0     

    CDDEV:
        name: Dev Deployment
        #runs-on: ubuntu-latest
        runs-on: self-hosted
        environment:
          name: dev
        needs: CI
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        
        steps:
          - name: Configure kubeconfig
            uses: azure/k8s-set-context@v1
            with:
              method: kubeconfig
              kubeconfig: ${{ env.K8S_KUBECONFIG }}
              #cluster-type: generic
            env:
              K8S_KUBECONFIG: ${{secrets.K8S_KUBECONFIG}}
              
          - name: Checkout Ansible Repo
            uses: actions/checkout@v2
            with:
              repository: 'julianoslackbr/ansible-kubernetes'

          - name: Install Ansible
            run: |
              pip3 install pip --upgrade
              pip3 install kubernetes==11.0.0 openshift==0.11.0
              pip3 install ansible==2.9

          - name: Create kubernets vars
            run:  ansible-playbook sample-playbook-createvars.yml -v
            env:
              TAG: ${{ needs.CI.outputs.SHORT_SHA }}

          - name: Create kubernets manifests
            run: ansible-playbook sample-playbook-k8s.yml -v 

          - name: Install kubeval test tool
            run: |
              curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
              tar xzf kubeval-linux-amd64.tar.gz -C /usr/local/bin/
              chmod +x /usr/local/bin/kubeval

          - name: Running kubeval test tool
            run: |
              for files in $(find ./k8s -type f); do
                /usr/local/bin/kubeval $files
                #test $? -ne 0 && exit 1
              done

          - name: Deploy kubernetes
            run: ansible-playbook sample-playbook-k8s.yml -v --extra-vars "deploy=true"
