name: Build and Deploy to Kubernets

on:
  push:
    branches:
      - dev

  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
jobs:

    build:
      name: Build Container
      runs-on: ubuntu-latest
      environment:
        name: ci
      env:
        GITHUB_SHA: ${{ github.sha }}
        
        REGISTRY_HOSTNAME: slackbr
        IMAGE_NAME: action-demo
      steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin

      - name: Set Github Short SHA
        run: |
          GITHUB_SHORT_SHA=$(echo "$GITHUB_SHA"|cut -c-5)
          export GITHUB_SHORT_SHA
          echo $GITHUB_SHORT_SHA
      
      - name: Build Docker image
        run: |
          #echo $GITHUB_SHORT_SHA
          docker build --file Dockerfile -t "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" .
          docker tag "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA" "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest
          
      - name: Push the image to Docker container registry
        run: |
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":"$GITHUB_SHA"
          docker push "$REGISTRY_HOSTNAME"/"$IMAGE_NAME":latest

    devSecrets:
      name: Dev Secrets Variables
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: "http://dev.teste.teste"
      needs: build
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      steps:
        
        - name: Checkout Ansible Repo
          uses: actions/checkout@v2
          with:
            repository: 'julianoslackbr/ansible-kubernetes'
            
        - name: Create Secrets vars
          run: |

            echo $SECRETS_CONTEXT > secrets.json
            cat secrets.json

            pip3 install pip --upgrade
            pip3 install kubernetes==11.0.0 openshift==0.11.0
            pip3 install ansible==2.9
            ansible-playbook sample-playbook-createvars.yml   
            cat secret-vars-file.yaml

        - uses: actions/upload-artifact@master
          with:
            name: secret-vars-file
            path: secret-vars-file.yaml      

    devKubernets:
        name: Dev Kubernetes Variables
        runs-on: ubuntu-latest
        environment:
          name: dev-k8s
        needs: build
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          container_tag: $GITHUB_SHA
          TESTE: ${{ github.sha }}

        steps:
          
          - name: Checkout Ansible Repo
            uses: actions/checkout@v2
            with:
              repository: 'julianoslackbr/ansible-kubernetes'
              
          - name: Create Kubernets vars
            run: |

              echo $SECRETS_CONTEXT > kubernetes.json
              cat kubernetes.json

              pip3 install pip --upgrade
              pip3 install kubernetes==11.0.0 openshift==0.11.0
              pip3 install ansible==2.9
              ansible-playbook sample-playbook-createvars.yml
              cat kubernetes-vars-file.yaml

          - uses: actions/upload-artifact@master
            with:
              name: kubernetes-vars-file
              path: kubernetes-vars-file.yaml      

    devDeployment:
        name: Deploy
        runs-on: ubuntu-latest
        environment:
          name: dev-k8s
        needs: [ devKubernets, devSecrets ]

        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
          container_tag: "$GITHUB_SHA"

        steps:
          
          - name: Checkout Ansible Repo
            uses: actions/checkout@v2
            with:
              repository: 'julianoslackbr/ansible-kubernetes'
              
          - name: Create Kubernets vars
            run: |

              echo $SECRETS_CONTEXT > kubernetes.json
              cat kubernetes.json

              pip3 install pip --upgrade
              pip3 install kubernetes==11.0.0 openshift==0.11.0
              pip3 install ansible==2.9
              ansible-playbook sample-playbook-createvars.yml
              cat kubernetes-vars-file.yaml

          - uses: actions/upload-artifact@master
            with:
              name: kubernetes-vars-file
              path: kubernetes-vars-file.yaml      

    # # deploy hml
    # hml:
    #   name: Hml Variables
    #   runs-on: ubuntu-latest
    #   environment:
    #     name: hml
    #     url: "http://hml.teste.teste"
    #   needs: deploy-dev

    #   steps:
    #     - name: Run hml deployment 
    #       run: |
    #         echo "Deploy HML"
    #         echo ${{ secrets.DB_HOST }} > file.txt
    #         cat file.txt
    #         printenv
    #         echo "-------"
    #         ls -al
            
  # Deploy the Docker image to the IKS cluster
      # - name: Deploy to IKS
      #   run: |
      #     ibmcloud ks cluster config --cluster $IKS_CLUSTER
      #     kubectl config current-context
      #     kubectl create deployment $DEPLOYMENT_NAME --image=$REGISTRY_HOSTNAME/$ICR_NAMESPACE/$IMAGE_NAME:$GITHUB_SHA --dry-run -o yaml > deployment.yaml
      #     kubectl apply -f deployment.yaml
      #     kubectl rollout status deployment/$DEPLOYMENT_NAME
      #     kubectl create service loadbalancer $DEPLOYMENT_NAME --tcp=80:$PORT --dry-run -o yaml > service.yaml
      #     kubectl apply -f service.yaml
      #     kubectl get services -o wide